[package]
name = "releasr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
serde = { version = "1.0.136", features = ["std", "derive", "serde_derive"] }
serde_yaml = "0.8.23"
yaml-rust = "0.4.5"
